# Generated by Django 5.2 on 2025-04-06 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_exam', models.CharField(choices=[('ENEM', 'ENEM'), ('CONCURSO', 'Concurso Público'), ('VESTIBULAR', 'Vestibular'), ('REFORCO', 'Reforço Escolar')], max_length=50)),
                ('available_hours_per_week', models.IntegerField(default=10)),
                ('learning_style', models.CharField(choices=[('video', 'Vídeo'), ('leitura', 'Leitura'), ('pratica', 'Prática'), ('misto', 'Misto')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('video', 'Vídeo'), ('leitura', 'Leitura'), ('exercicio', 'Exercício'), ('flashcard', 'Flashcard')], max_length=50)),
                ('scheduled_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study.studyplan')),
            ],
        ),
    ]
