# Generated by Django 5.1.8 on 2025-04-07 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.content'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='questions',
            field=models.ManyToManyField(to='study.question'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_study_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyprogress',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.content'),
        ),
        migrations.AddField(
            model_name='studyprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='study.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='studyprogress',
            unique_together={('user', 'content')},
        ),
    ]
