# Generated by Django 5.2 on 2025-04-06 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('pdf', 'PDF')], max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='available_hours_per_week',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='learning_style',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='target_exam',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='title',
        ),
        migrations.RemoveField(
            model_name='studytask',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='studytask',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='studytask',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='studytask',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='studytask',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='goal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='daily_study_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='study_study_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studytask',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.content')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(to='study.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='study.subject'),
        ),
    ]
