# Generated by Django 5.1.8 on 2025-04-07 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_disciplina_options_alter_materialpdf_options_and_more'),
        ('study', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_conclusao', models.FloatField(default=0.0)),
                ('acertos', models.IntegerField(default=0)),
                ('erros', models.IntegerField(default=0)),
                ('tempo_estudo', models.DurationField(default='00:00:00')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_estudo', to='content.disciplina')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresso_estudo', to='content.quiz')),
                ('topico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresso_estudo', to='content.topico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_estudo', to=settings.AUTH_USER_MODEL)),
                ('video_aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresso_estudo', to='content.videoaula')),
            ],
            options={
                'ordering': ['-ultima_atualizacao'],
                'unique_together': {('usuario', 'disciplina', 'topico', 'video_aula', 'quiz')},
            },
        ),
    ]
