# Generated by Django 5.1.8 on 2025-04-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processed', 'Processada'), ('error', 'Erro')], default='pending', max_length=10),
        ),
    ]
