# Generated by Django 5.1.8 on 2025-04-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_mensagem_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
