# Generated by Django 5.1.8 on 2025-04-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_disciplina_topico_materialpdf_topico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='materialpdf',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterModelOptions(
            name='topico',
            options={'ordering': ['nome']},
        ),
    ]
