# Generated by Django 5.1.8 on 2025-04-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='desempenho',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='metas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
