# Generated by Django 5.1.8 on 2025-04-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_curso_user_desempenho_user_metas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estilo_aprendizado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='horas_estudo',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trilha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
