# Generated by Django 5.1.8 on 2025-04-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_estilo_aprendizado_user_horas_estudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
