# Generated by Django 5.1.8 on 2025-04-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar_user_nivel_user_xp_alter_user_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
